# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: svelte

# The type key specifies the language and version for your application.
type: 'nodejs:16'

# The hooks that will be triggered when the package is deployed.
hooks:
    build: |
        set -e
        npm run build
# The size of the persistent disk of the application (in MB).
disk: 1024

web:
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'build'
            passthru: true
            index: ['index.html']
            scripts: false
            allow: true
            expires: 24h
            rules:
                \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|cast|mp4|json|yaml|ico|svg?|cast|mp4|json|yaml|svg?|ttf)$:
                    expires: 4w
