name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  test-svelte:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: svelte
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: |
        npm run format:images
        npm run build
    - name: Test
      run: npm run test
